### ISSUE TITLE
Discrepancy in Input and Output S3 URL Paths in Online-Monitoring Section of Demo App

### ISSUE THREAD

**Issue by polineniavinash** [aws-samples/amazon-lookout-for-equipment-demo-app#13]
Hello,

I've encountered an issue with the Amazon Lookout for Equipment Demo App, specifically regarding the S3 URL paths used in the online-monitoring component. It appears that there is a discrepancy between the S3 paths defined in the demo app and the actual S3 bucket locations where the data resides.

Issue Description:
Expected S3 Paths (as per the demo app):

Input Location: s3://amazonl4e-testapp-23232j2llk32l3k/inference-data/223233-model-1/input/
Output Location: s3://amazonl4e-testapp-23232j2llk32l3k/inference-data/223233-model-1/output/
Actual S3 Paths (as observed in AWS):

Input Location: s3://amazonl4e-testapp-23232j2llk32l3k/inference-data/223233-test-amazon-l4e-project-model-1/input/
Output Location: s3://amazonl4e-testapp-23232j2llk32l3k/inference-data/223233-test-amazon-l4e-project-model-1/output/
The paths in the demo app are missing the project name segment (test-amazon-l4e-project), which leads to confusion and potential misconfiguration when users are trying to integrate or test the solution.

Impact:
This discrepancy can cause users to incorrectly configure their AWS environment, leading to potential issues in data processing and anomaly detection.

Suggested Fix:
It would be beneficial for the accuracy and usability of the demo app if the S3 URL paths are updated to reflect the actual structure used in AWS, including the project name segment.

Thank you for your attention to this matter. I look forward to the resolution and update of the demo app.

Best regards,
Avinash Polineni

**Comment by michaelhoarau** [comment]
Thanks for your feedback, the location was correct in the deployment dialog box, but not in the scheduler inspector in the online monitoring page. This is now corrected.

**Comment by polineniavinash** [comment]
Thank You!
