### ISSUE TITLE
Persistent Issue with Model Deletion in Amazon Lookout for Equipment Demo App

### ISSUE THREAD

**Issue by polineniavinash** [aws-samples/amazon-lookout-for-equipment-demo-app#15]
Hello,

I am writing to report a persistent issue encountered with the Amazon Lookout for Equipment Demo App, specifically in the model training section where models cannot be successfully deleted.

Issue Description:
Problem: When attempting to delete a model from the model training section of the demo app, the UI prompts with the 'Delete Model' option. However, upon selecting this option, the app enters a never-ending loading loop. Post this loop, when checked back, the model still remains undeleted in the system.

Expected Behavior: On selecting the 'Delete Model' option, the model should be successfully removed from the system, with appropriate confirmation to the user.

Actual Behavior: The model remains undeleted despite multiple attempts, with the UI getting stuck in a loading loop, leading to user confusion and inability to manage the models efficiently.

Impact:
This issue hinders the effective management of models within the demo app. Users are unable to delete outdated or unnecessary models, potentially leading to clutter and confusion, especially in environments where multiple models are being tested or used.

Steps to Reproduce:
Go to the model training section of the Amazon Lookout for Equipment Demo App.
Select a model to be deleted.
Click on the 'Delete Model' option.
Observe the UI entering a never-ending loading loop.
After exiting the loop, check to see if the model has been deleted.
Suggested Fix:
A review and fix of the model deletion functionality within the app would be greatly appreciated. Ensuring that the models can be deleted as intended would significantly improve the user experience and the app's manageability.

I appreciate your prompt attention to this matter and look forward to a resolution that will enhance the functionality of the demo app.

Best regards,
Avinash Polineni

**Comment by polineniavinash** [comment]
Upon further investigation, I've realized that the inability to delete the model might be due to an attached inference scheduler. It appears that the model cannot be removed while the inference scheduler is still active. Currently, there seems to be no option to delete the inference scheduler from within the demo app itself.

As a workaround, I believe that deleting the inference scheduler directly from the AWS UI might allow for successful model deletion. However, for future usability and clarity, it would be beneficial if the demo app included a feature for managing or deleting inference schedulers, or at least a notification or ribbon indicating that deletion of the inference scheduler is a prerequisite for model removal.

This additional feature or notification could greatly enhance the user experience and help avoid confusion regarding model management within the app.

**Comment by michaelhoarau** [comment]
You are correct, this was linked to models with attached schedulers. The scheduler was incorrectly detected. This is corrected and this is the behavior you should now see:

![model-delete-with-scheduler](https://github.com/aws-samples/amazon-lookout-for-equipment-demo-app/assets/12375366/d88691cb-cfc4-4f3d-bc70-2111f620bbcd)

**Comment by polineniavinash** [comment]
Wow, Thanks for the prompt resolution and response.
